"""added attempts column to the reminders table

Revision ID: 129e8d925b60
Revises: d71aab1858c9
Create Date: 2026-10-03 10:46:13.868600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '129e8d925b60'
down_revision: Union[str, Sequence[str], None] = 'd71aab1858c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('reminders', sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
  


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('reminders', 'attempts')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('group_chat_messages', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_constraint('uq_chat_read_position', 'chat_read_positions', type_='unique')
    op.create_table('contacts',
    sa.Column('contact_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('contacts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', name=op.f('contacts_pkey')),
    sa.UniqueConstraint('email', name=op.f('contacts_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('chat',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reciever_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.user_id'], name=op.f('chat_reciever_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('chat_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('chat_pkey'))
    )
    op.create_index(op.f('ix_messages_sender__recipient'), 'chat', ['sender_id', 'reciever_id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_sender'), 'chat', ['reciever_id', 'sender_id'], unique=False)
    # ### end Alembic commands ###
