"""added bio to the business table

Revision ID: 1ed17afb1eb0
Revises: 9f48231ccce2
Create Date: 2026-06-27 07:37:21.633766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed17afb1eb0'
down_revision: Union[str, Sequence[str], None] = '9f48231ccce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('debt_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'bio')
    # ### end Alembic commands ###
