"""removed refresh column

Revision ID: 29794cd10fb3
Revises: 1ed17afb1eb0
Create Date: 2026-07-09 03:00:45.295419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29794cd10fb3'
down_revision: Union[str, Sequence[str], None] = '1ed17afb1eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
