"""made the reminders table rows nullable and enforce security with pydantic sche

Revision ID: 2a7d1524227d
Revises: 6ab7e59575e3
Create Date: 2026-09-01 13:36:42.131988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7d1524227d'
down_revision: Union[str, Sequence[str], None] = '6ab7e59575e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'debt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reminders', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reminders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reminders', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reminders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reminders', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reminders', 'debt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
