"""added debt table

Revision ID: 2dede6b41206
Revises: 1f240fd30bcc
Create Date: 2026-06-06 12:32:14.978969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dede6b41206'
down_revision: Union[str, Sequence[str], None] = '1f240fd30bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'manager', 'cashier', 'viewer', 'user', name='roleenum'),
               nullable=True)
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('customers', 'debt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('debt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('customers', 'address')
    op.alter_column('approvals', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'manager', 'cashier', 'viewer', 'user', name='roleenum'),
               nullable=False)
    # ### end Alembic commands ###
