"""add role

Revision ID: 2fa6b9e76f0a
Revises: b5d9208c648d
Create Date: 2026-05-19 10:35:59.105964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa6b9e76f0a'
down_revision: Union[str, Sequence[str], None] = 'b5d9208c648d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('role', sa.Enum('super_admin', 'admin', 'user', 'manager', 'cashier', 'viewer', name='roleenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvals', 'role')
    # ### end Alembic commands ###
