"""add ondelete and nullable to approvals fk

Revision ID: 38bf1073d056
Revises: 760bb19b446f
Create Date: 2026-07-13 17:16:12.471091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38bf1073d056'
down_revision: Union[str, Sequence[str], None] = '760bb19b446f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('approvals_business_id_fkey'), 'approvals', type_='foreignkey')
    op.drop_constraint(op.f('approvals_reviewer_id_fkey'), 'approvals', type_='foreignkey')
    op.drop_constraint(op.f('approvals_requester_id_fkey'), 'approvals', type_='foreignkey')
    op.create_foreign_key(None, 'approvals', 'businesses', ['business_id'], ['business_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'approvals', 'users', ['reviewer_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'approvals', 'users', ['requester_id'], ['user_id'], ondelete='SET NULL')
    op.execute("UPDATE users SET is_verified = 'false' WHERE is_verified IS NULL")
    op.execute("ALTER TABLE users ALTER COLUMN is_verified TYPE BOOLEAN USING is_verified::BOOLEAN")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.create_foreign_key(op.f('approvals_requester_id_fkey'), 'approvals', 'users', ['requester_id'], ['user_id'])
    op.create_foreign_key(op.f('approvals_reviewer_id_fkey'), 'approvals', 'users', ['reviewer_id'], ['user_id'])
    op.create_foreign_key(op.f('approvals_business_id_fkey'), 'approvals', 'businesses', ['business_id'], ['business_id'])
    op.alter_column('approvals', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
