"""added relationship between sale and debt table

Revision ID: 3a4665428505
Revises: 2dede6b41206
Create Date: 2026-06-06 13:02:18.706111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4665428505'
down_revision: Union[str, Sequence[str], None] = '2dede6b41206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'debts', 'sales', ['sale_id'], ['sale_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.drop_column('debts', 'sale_id')
    # ### end Alembic commands ###
