"""modify the transaction table

Revision ID: 3c07213b90da
Revises: e54fd413d5e4
Create Date: 2026-07-18 16:06:31.552652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c07213b90da'
down_revision: Union[str, Sequence[str], None] = 'e54fd413d5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.debt_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.drop_table('debt_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_transactions',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('debt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remainder', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.debt_id'], name=op.f('debt_transactions_debt_id_fkey')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('debt_transactions_pkey'))
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###
