"""set nullable to true

Revision ID: 760bb19b446f
Revises: 29794cd10fb3
Create Date: 2026-07-13 17:13:21.005670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760bb19b446f'
down_revision: Union[str, Sequence[str], None] = '29794cd10fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('approvals_business_id_fkey'), 'approvals', type_='foreignkey')
    op.drop_constraint(op.f('approvals_reviewer_id_fkey'), 'approvals', type_='foreignkey')
    op.drop_constraint(op.f('approvals_requester_id_fkey'), 'approvals', type_='foreignkey')
    op.create_foreign_key(None, 'approvals', 'users', ['requester_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'approvals', 'businesses', ['business_id'], ['business_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'approvals', 'users', ['reviewer_id'], ['user_id'], ondelete='SET NULL')
    op.alter_column('users', 'is_verified',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.create_foreign_key(op.f('approvals_requester_id_fkey'), 'approvals', 'users', ['requester_id'], ['user_id'])
    op.create_foreign_key(op.f('approvals_reviewer_id_fkey'), 'approvals', 'users', ['reviewer_id'], ['user_id'])
    op.create_foreign_key(op.f('approvals_business_id_fkey'), 'approvals', 'businesses', ['business_id'], ['business_id'])
    op.alter_column('approvals', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
