"""addedperformer column on transaction table

Revision ID: 793c08d3c0f9
Revises: 3c07213b90da
Create Date: 2026-07-18 17:30:14.041251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793c08d3c0f9'
down_revision: Union[str, Sequence[str], None] = '3c07213b90da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('performer_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('business_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'transactions', 'businesses', ['business_id'], ['business_id'])
    op.create_foreign_key(None, 'transactions', 'users', ['performer_id'], ['user_id'])
    op.create_foreign_key(None, 'transactions', 'customers', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('transactions', 'customer_id')
    op.drop_column('transactions', 'business_id')
    op.drop_column('transactions', 'performer_id')
    # ### end Alembic commands ###
