"""added is_verified column

Revision ID: 9f48231ccce2
Revises: e863553eaed9
Create Date: 2026-06-20 09:22:50.573878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f48231ccce2'
down_revision: Union[str, Sequence[str], None] = 'e863553eaed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debts', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('debts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('is_verified', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.alter_column('debts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('debts', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
