"""sms_rec_limit

Revision ID: cba1ec5841c6
Revises: b7e21c4a9f03
Create Date: 2026-10-08 16:07:13.206628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cba1ec5841c6'
down_revision: Union[str, Sequence[str], None] = 'b7e21c4a9f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column('sales', 'sms_no_sales_rec_lim')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_refresh_sessions_session_id'), table_name='refresh_sessions')
    op.create_index(op.f('ix_refresh_sessions_session_id'), 'refresh_sessions', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('refresh_sessions_token_hash_key'), 'refresh_sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('refresh_sessions_session_id_key'), 'refresh_sessions', ['session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('group_chat_messages', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_constraint('uq_chat_read_position', 'chat_read_positions', type_='unique')
    op.create_table('chat',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reciever_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.user_id'], name=op.f('chat_reciever_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('chat_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('chat_pkey'))
    )
    op.create_index(op.f('ix_messages_sender__recipient'), 'chat', ['sender_id', 'reciever_id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_sender'), 'chat', ['reciever_id', 'sender_id'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('contacts',
    sa.Column('contact_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('contacts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', name=op.f('contacts_pkey')),
    sa.UniqueConstraint('email', name=op.f('contacts_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
