"""fixed the relationship issues

Revision ID: dd1375ae8aeb
Revises: a86d7ed2d2ca
Create Date: 2026-09-02 17:47:30.554247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd1375ae8aeb'
down_revision: Union[str, Sequence[str], None] = 'a86d7ed2d2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('business_members', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('business_members_business_id_fkey'), 'business_members', type_='foreignkey')
    op.drop_constraint(op.f('business_members_user_id_fkey'), 'business_members', type_='foreignkey')
    op.create_foreign_key(None, 'business_members', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'business_members', 'businesses', ['business_id'], ['business_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('customers_business_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['business_id'], ondelete='CASCADE')
    op.alter_column('debts', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('debts_sale_id_fkey'), 'debts', type_='foreignkey')
    op.drop_constraint(op.f('debts_customer_id_fkey'), 'debts', type_='foreignkey')
    op.drop_constraint(op.f('debts_business_id_fkey'), 'debts', type_='foreignkey')
    op.create_foreign_key(None, 'debts', 'businesses', ['business_id'], ['business_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'debts', 'sales', ['sale_id'], ['sale_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'debts', 'customers', ['customer_id'], ['customer_id'], ondelete='RESTRICT')
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'cost_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('reminders', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('reminders', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('reminders_debt_id_fkey'), 'reminders', type_='foreignkey')
    op.drop_constraint(op.f('reminders_customer_id_fkey'), 'reminders', type_='foreignkey')
    op.drop_constraint(op.f('reminders_business_id_fkey'), 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'businesses', ['business_id'], ['business_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reminders', 'debts', ['debt_id'], ['debt_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reminders', 'customers', ['customer_id'], ['customer_id'], ondelete='SET NULL')
    op.alter_column('sales', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('sales', 'amount_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sales', 'profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_constraint(op.f('sales_business_id_fkey'), 'sales', type_='foreignkey')
    op.drop_constraint(op.f('sales_user_id_fkey'), 'sales', type_='foreignkey')
    op.drop_constraint(op.f('sales_customer_id_fkey'), 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'businesses', ['business_id'], ['business_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['customer_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('sales_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('sales_items', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sales_items', 'profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('sales_items_sale_id_fkey'), 'sales_items', type_='foreignkey')
    op.drop_constraint(op.f('sales_items_product_id_fkey'), 'sales_items', type_='foreignkey')
    op.create_foreign_key(None, 'sales_items', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales_items', 'sales', ['sale_id'], ['sale_id'], ondelete='CASCADE')
    op.alter_column('transactions', 'performer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('transactions_debt_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_customer_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_business_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_performer_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'customers', ['customer_id'], ['customer_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'businesses', ['business_id'], ['business_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'debts', ['debt_id'], ['debt_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'users', ['performer_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_performer_id_fkey'), 'transactions', 'users', ['performer_id'], ['user_id'])
    op.create_foreign_key(op.f('transactions_business_id_fkey'), 'transactions', 'businesses', ['business_id'], ['business_id'])
    op.create_foreign_key(op.f('transactions_customer_id_fkey'), 'transactions', 'customers', ['customer_id'], ['customer_id'])
    op.create_foreign_key(op.f('transactions_debt_id_fkey'), 'transactions', 'debts', ['debt_id'], ['debt_id'])
    op.alter_column('transactions', 'performer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'sales_items', type_='foreignkey')
    op.drop_constraint(None, 'sales_items', type_='foreignkey')
    op.create_foreign_key(op.f('sales_items_product_id_fkey'), 'sales_items', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key(op.f('sales_items_sale_id_fkey'), 'sales_items', 'sales', ['sale_id'], ['sale_id'])
    op.alter_column('sales_items', 'profit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('sales_items', 'subtotal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('sales_items', 'unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(op.f('sales_customer_id_fkey'), 'sales', 'customers', ['customer_id'], ['customer_id'])
    op.create_foreign_key(op.f('sales_user_id_fkey'), 'sales', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('sales_business_id_fkey'), 'sales', 'businesses', ['business_id'], ['business_id'])
    op.alter_column('sales', 'profit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sales', 'amount_paid',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key(op.f('reminders_business_id_fkey'), 'reminders', 'businesses', ['business_id'], ['business_id'])
    op.create_foreign_key(op.f('reminders_customer_id_fkey'), 'reminders', 'customers', ['customer_id'], ['customer_id'])
    op.create_foreign_key(op.f('reminders_debt_id_fkey'), 'reminders', 'debts', ['debt_id'], ['debt_id'])
    op.alter_column('reminders', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reminders', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('products', 'cost_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.create_foreign_key(op.f('debts_business_id_fkey'), 'debts', 'businesses', ['business_id'], ['business_id'])
    op.create_foreign_key(op.f('debts_customer_id_fkey'), 'debts', 'customers', ['customer_id'], ['customer_id'])
    op.create_foreign_key(op.f('debts_sale_id_fkey'), 'debts', 'sales', ['sale_id'], ['sale_id'])
    op.alter_column('debts', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_business_id_fkey'), 'customers', 'businesses', ['business_id'], ['business_id'])
    op.drop_constraint(None, 'business_members', type_='foreignkey')
    op.drop_constraint(None, 'business_members', type_='foreignkey')
    op.create_foreign_key(op.f('business_members_user_id_fkey'), 'business_members', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('business_members_business_id_fkey'), 'business_members', 'businesses', ['business_id'], ['business_id'])
    op.alter_column('business_members', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('business_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
