"""add business key

Revision ID: ecbb17304f9f
Revises: 739882d3e9d7
Create Date: 2026-05-15 11:24:07.434244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbb17304f9f'
down_revision: Union[str, Sequence[str], None] = '739882d3e9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('business_key', sa.String(), nullable=True))
    op.drop_constraint(op.f('businesses_api_key_key'), 'businesses', type_='unique')
    op.create_unique_constraint(None, 'businesses', ['business_key'])
    op.drop_column('businesses', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'businesses', type_='unique')
    op.create_unique_constraint(op.f('businesses_api_key_key'), 'businesses', ['api_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('businesses', 'business_key')
    # ### end Alembic commands ###
