"""added is active to customer table

Revision ID: fd810ed592b2
Revises: a38971245647
Create Date: 2026-06-07 13:01:48.156738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd810ed592b2'
down_revision: Union[str, Sequence[str], None] = 'a38971245647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default="True"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
