import smtplib
from email.mime.text import MIMEText
import os
from dotenv import load_dotenv
import time

load_dotenv()


class EmailReport:
    def __init__(self, to_email: str, subject: str, body: dict):
        self.to_email = to_email
        self.subject = subject
        self.body = body
        self.Email = os.getenv("SUPER_ADMIN_EMAIL")
        self.Password = os.getenv("SUPER_ADMIN_APP_PASSWORD")
        self.name = os.getenv("SUPER_ADMIN_NAME")

    def prepare_message(self) -> MIMEText:
        html_body = f"""
        <html>
        <body style="margin:0; padding:0; background:#f4f6f9; font-family: Arial, sans-serif;">
        <div style="max-width:580px; margin:32px auto; background:#ffffff; border-radius:10px; overflow:hidden; border:1px solid #e0e0e0;">

            <div style="background:#1a3a6b; padding:28px 32px;">
            <p style="color:#a8c4e8; font-size:12px; margin:0 0 4px; letter-spacing:0.5px;">AUTOMATED REPORT</p>
            <h1 style="color:#ffffff; font-size:22px; font-weight:600; margin:0 0 4px;">{self.subject}</h1>
            <p style="color:#a8c4e8; font-size:13px; margin:0;">{self.body['date']} — {self.body['end_date']}</p>
            </div>

            <div style="padding:24px 32px;">

            <div style="display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-bottom:24px;">
                <div style="background:#f7f9fc; border-radius:8px; padding:16px;">
                <p style="font-size:12px; color:#888; margin:0 0 6px;">Total Revenue</p>
                <p style="font-size:22px; font-weight:600; color:#1a1a1a; margin:0;">GHS {self.body['total_revenue']:,.2f}</p>
                </div>
                <div style="background:#f7f9fc; border-radius:8px; padding:16px;">
                <p style="font-size:12px; color:#888; margin:0 0 6px;">Total Profit</p>
                <p style="font-size:22px; font-weight:600; color:#1a7a4a; margin:0;">GHS {self.body['total_profit']:,.2f}</p>
                </div>
                <div style="background:#f7f9fc; border-radius:8px; padding:16px;">
                <p style="font-size:12px; color:#888; margin:0 0 6px;">Total Orders</p>
                <p style="font-size:22px; font-weight:600; color:#1a1a1a; margin:0;">{self.body['total_sales']}</p>
                </div>
                <div style="background:#f7f9fc; border-radius:8px; padding:16px;">
                <p style="font-size:12px; color:#888; margin:0 0 6px;">Units Sold</p>
                <p style="font-size:22px; font-weight:600; color:#1a1a1a; margin:0;">{self.body['sold_quantity']}</p>
                </div>
            </div>

            <div style="border:1px solid #e0e0e0; border-radius:8px; overflow:hidden; margin-bottom:24px;">
                <div style="padding:12px 16px; background:#f7f9fc; border-bottom:1px solid #e0e0e0;">
                <p style="font-size:13px; font-weight:600; color:#1a1a1a; margin:0;">Payment breakdown</p>
                </div>
                <div style="padding:0 16px;">
                <div style="display:flex; justify-content:space-between; padding:12px 0; border-bottom:1px solid #f0f0f0;">
                    <span style="font-size:14px; color:#555;">Cash</span>
                    <span style="font-size:14px; font-weight:600; color:#1a1a1a;">{self.body['cash_total']:,.2f}</span>
                </div>
                <div style="display:flex; justify-content:space-between; padding:12px 0; border-bottom:1px solid #f0f0f0;">
                    <span style="font-size:14px; color:#555;">Mobile money</span>
                    <span style="font-size:14px; font-weight:600; color:#1a1a1a;">{self.body['momo_total']:,.2f}</span>
                </div>
                <div style="display:flex; justify-content:space-between; padding:12px 0;">
                    <span style="font-size:14px; color:#555;">Card</span>
                    <span style="font-size:14px; font-weight:600; color:#1a1a1a;">{self.body['card_total']:,.2f}</span>
                </div>
                </div>
            </div>

            <div style="background:#f0f7ff; border:1px solid #b5d4f4; border-radius:8px; padding:14px 16px; margin-bottom:24px;">
                <p style="font-size:12px; color:#185fa5; margin:0 0 4px;">Best selling product</p>
                <p style="font-size:15px; font-weight:600; color:#0c447c; margin:0;">{self.body['best_selling_product']}</p>
            </div>

            <div style="border-top:1px solid #e0e0e0; padding-top:20px;">
                <p style="font-size:13px; color:#aaa; margin:0;">This is an automated report generated by your Sales Tracker. Do not reply to this email.</p>
            </div>

            </div>
        </div>
        </body>
        </html>
        """
        message = MIMEText(html_body, 'html')
        message['From'] = f"{self.name} <{self.Email}>"
        message['To'] = self.to_email
        message['Subject'] = self.subject
        return message

    def send(self):
        message = self.prepare_message()

        for attempts in range(5):
            try:
                with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                    server.login(self.Email, self.Password)
                    server.sendmail(from_addr=self.Email, to_addrs=self.to_email, msg=message.as_string())
                    break
            except Exception as e:
                print(f"Attempt {attempts + 1} failed: {e}")
                time.sleep(10)
